<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="jazzy_bot">

  <!-- ========== PROPERTIES ========== -->
  <xacro:property name="base_width" value="0.4" />
  <xacro:property name="base_length" value="0.5" />
  <xacro:property name="base_height" value="0.2" />
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_width" value="0.05" />
  <xacro:property name="wheel_separation" value="0.45" />
  <xacro:property name="caster_radius" value="0.05" />

  <!-- ========== MATERIALS ========== -->
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1.0" />
  </material>

  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0" />
  </material>

  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0" />
  </material>

  <!-- ========== BASE LINK ========== -->
  <link name="base_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <box size="${base_length} ${base_width} ${base_height}" />
    </geometry>
    <material name="blue" />
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <box size="${base_length} ${base_width} ${base_height}" />
    </geometry>
  </collision>
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <mass value="10.0" />
    <inertia ixx="0.133" ixy="0.0" ixz="0.0" iyy="0.258" iyz="0.0" izz="0.258" />
  </inertial>
  </link>

  <!-- ========== WHEEL MACRO ========== -->
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
            <slip1>0.0</slip1>
            <slip2>0.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="1.0" />
      <inertia ixx="0.00325" ixy="0.0" ixz="0.0" iyy="0.00325" iyz="0.0" izz="0.005" />
    </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="${prefix}_wheel" />
      <origin xyz="0 ${reflect * wheel_separation/2} ${-base_height/2 + 0.01}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>

  <!-- ========== INSTANTIATE WHEELS ========== -->
  <xacro:wheel prefix="left" reflect="1" />
  <xacro:wheel prefix="right" reflect="-1" />

    <!-- ========== FRONT CASTER WHEEL ========== -->
  <link name="front_caster">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${caster_radius}" />
      </geometry>
      <material name="gray" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${caster_radius}" />
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.0</mu>
            <mu2>0.0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.5" />
      <inertia ixx="0.0005" ixy="0.0" ixz="0.0" iyy="0.0005" iyz="0.0" izz="0.0005" />
    </inertial>
  </link>

  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link" />
    <child link="front_caster" />
    <!-- Letakkan di depan: x = + (base_length/2 - offset) -->
    <origin xyz="${base_length/2 - caster_radius} 0 ${-base_height/2 - caster_radius/2}" rpy="0 0 0" />
  </joint>

  <!-- ========== CASTER WHEEL ========== -->
  <link name="caster_wheel">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <sphere radius="${caster_radius}" />
    </geometry>
    <material name="gray" />
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <sphere radius="${caster_radius}" />
    </geometry>
    <surface>
      <friction>
        <ode>
          <mu>0.0</mu>
          <mu2>0.0</mu2>
          <slip1>1.0</slip1>
          <slip2>1.0</slip2>
        </ode>
      </friction>
    </surface>
  </collision>
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <mass value="0.5" />
    <inertia ixx="0.0005" ixy="0.0" ixz="0.0" iyy="0.0005" iyz="0.0" izz="0.0005" />
  </inertial>
  </link>

  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link" />
    <child link="caster_wheel" />
    <origin xyz="${-base_length/2 + caster_radius} 0 ${-base_height/2 - caster_radius/2}" rpy="0 0 0" />
  </joint>


  <!--==========LIDAR SENSOR LINK==========-->
  <link name="lidar_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <cylinder radius="0.05" length="0.04" />
    </geometry>
    <material name="black" />
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <cylinder radius="0.05" length="0.04" />
    </geometry>
  </collision>
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <mass value="0.2" />
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
  </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link" />
    <child link="lidar_link" />
    <origin xyz="${base_length/4} 0 ${base_height/2 + 0.02}" rpy="0 0 0" />
  </joint>

  <!-- ========== GAZEBO PLUGINS ========== -->

  <!-- Differential Drive Plugin -->
  <gazebo>
    <plugin filename="libgz-sim-diff-drive-system.so" name="gz::sim::systems::DiffDrive">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>30</odom_publish_frequency>
      <max_linear_acceleration>2.0</max_linear_acceleration>
      <min_linear_acceleration>-2.0</min_linear_acceleration>
      <max_angular_acceleration>3.0</max_angular_acceleration>
      <min_angular_acceleration>-3.0</min_angular_acceleration>
      <max_linear_velocity>1.0</max_linear_velocity>
      <min_linear_velocity>-0.5</min_linear_velocity>
      <max_angular_velocity>2.0</max_angular_velocity>
      <min_angular_velocity>-2.0</min_angular_velocity>
    </plugin>
  </gazebo>


  <gazebo>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
  </gazebo>

  <!-- LiDAR Sensor Plugin (FIXED, ROS2-compatible) -->
  <gazebo reference="lidar_link">
    <sensor name="gpu_lidar" type="gpu_lidar">
      <topic>scan</topic>
      <update_rate>10</update_rate>
      <always_on>true</always_on>
      <visualize>true</visualize>
      <lidar>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
          <!-- <vertical>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </vertical> -->
        </scan>
        <range>
          <min>0.05</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </lidar>
      <gz_frame_id>lidar_link</gz_frame_id>
    </sensor>
  </gazebo>




  <!-- ========== GAZEBO MATERIALS ========== -->
  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="left_wheel">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="right_wheel">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="caster_wheel">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="lidar_link">
    <material>Gazebo/Black</material>
  </gazebo>

</robot>